# Site settings
title: KEBEBASAN
description: "Bebaskan diri dari penghambaan kepada selain ALLAH Azza wa Jalla"
url: "https://kebebasan.id"
author:
  name: "SANREMEMBER"
  email: "sanremember@gmx.com"
  url: "https://kebebasan.id"

# Build settings
baseurl: # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:year/:month/:day/:title/
paginate: 8
paginate_path: /halaman-:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

gems:
  - jekyll-paginate
